version: '3.8'

services:
  app:
    image: php:8.4-cli
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y libzip-dev zip unzip git curl libpng-dev libonig-dev libxml2-dev &&
        docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd zip &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        composer install --no-dev --optimize-autoloader &&
        php artisan key:generate &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
