# WARNING: Netlify does not natively support PHP/Laravel applications
# This configuration is for static asset deployment only
# For full Laravel functionality, consider using:
# - Vercel (supports PHP)
# - Railway
# - DigitalOcean App Platform
# - Heroku
# - AWS Elastic Beanstalk

[build]
  publish = "public"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Static assets only - PHP functionality will NOT work on Netlify
[[redirects]]
  from = "/build/*"
  to = "/build/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

# Fallback - will serve static index.html if it exists
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
