services:
  - type: web
    name: fofana-stock-tracker
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: "Fofana Stock Tracker"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: fofana-stock-tracker
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-eu-west-3.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.fiirszqosyhhuqbpbily
      - key: DB_PASSWORD
        value: xhCtn3oRTksrcmc6
      - key: DB_SSLMODE
        value: require
      - key: SUPABASE_URL
        value: https://fiirszqosyhhuqbpbily.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpaXJzenFvc3loaHVxYnBiaWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDc3MzksImV4cCI6MjA3MjQyMzczOX0.h2hgkg0djW110DODX6MkAeBFHot2V5Nx66rCXBB9QSY
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpaXJzenFvc3loaHVxYnBiaWx5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Njg0NzczOSwiZXhwIjoyMDcyNDIzNzM5fQ.ZLaEoiieiD96Q2il_CsAboBzfPtxlPQimpEMHBraVuA
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: PORT
        value: 80

# Optional: PostgreSQL database (commented out since we're using SQLite)
# databases:
#   - name: fofana-db
#     plan: free
#     databaseName: fofana_stock_tracker
