version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-management
    container_name: stock-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - stock-network

  nginx:
    image: nginx:alpine
    container_name: stock-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - stock-network

  db:
    image: postgres:latest
    container_name: stock-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - stock-network

  redis:
    image: redis:alpine
    container_name: stock-redis
    restart: unless-stopped
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 